const { Client, MessageAttachment, MessageCollector, MessageEmbed } = require("discord.js")
const client = new Client()
const { Bot, Guild, Ekip } = require("./maveraktria.json") 
const buttons = require("discord-buttons")
buttons(client)
